COMP: Fix linking of igtlutil when built from inside Slicer
Without this, the following link error are reported:

/home/jcfr/Projects/NIRFASTSlicer-RelWithDebInfo/OpenIGTLink/Source/igtlutil/igtl_image.c:121: undefined reference to `sqrtf'
/home/jcfr/Projects/NIRFASTSlicer-RelWithDebInfo/OpenIGTLink/Source/igtlutil/igtl_image.c:123: undefined reference to `sqrtf'
/home/jcfr/Projects/NIRFASTSlicer-RelWithDebInfo/OpenIGTLink/Source/igtlutil/igtl_image.c:122: undefined reference to `sqrtf'

This happens because the flag "-Wl,--no-undefined" is set in Slicer.